server {
  listen 80;
  server_name _;

  # if ($http_x_forwarded_for !~ ^(137.59.100.135|180.167.119.206|223.166.93.104|150.249.204.83|106.184.149.26|106.184.135.198|221.241.21.122)) {
  #   return 403;
  # }

  # 通用 scene 路由：scene-01 ~ scene-07
  location ~ ^/webview/Beatgame2026/(scene-0[1-7])(/|$) {
      alias /data/web/galgame_v16/$1/;
      index index.html;
      try_files $uri $uri/ /index.html =404;
  }

  location / {
    root /data/web;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /data/web;
  }
}

